name: Update YouTube
on:
  schedule:
    - cron: "0 * * * *" # Runs every hour, on the hour
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCixa1fTqnDgZ9RWccidLgzg
          comment_tag_name: YOUTUBE-CARDS
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
          show_duration: true
          readme_path: insignia-interactive/.github/blob/main/profile/README.md
